const items = {
  body_neck_bells_christmas_2023: {title: 'Christmas Bells'},
  body_neck_bowtie_noir_detective: {title: 'Bowtie'},
  checkpoint_avatar_old: {title: 'Mini Me'},
  checkpoint_backpack_school: {title: 'School Bag Checkpoint'},
  checkpoint_balloon_heart: {title: 'Heart-shaped Balloon'},
  checkpoint_balloon_new_year_2024: {title: 'Balloon 2024 Checkpoint'},
  checkpoint_briefcase_noir_detective: {title: 'Briefcase Checkpoint'},
  checkpoint_chair_folding: {title: 'Folding Chair Checkpoint'},
  checkpoint_cheese_basic: {title: 'Cheesepoint'},
  checkpoint_egg_basic_circles: {title: 'Easter Egg 2'},
  checkpoint_egg_basic_dots: {title: 'Easter Egg 1'},
  checkpoint_fireworks_new_year_2024: {title: 'Fireworks Checkpoint'},
  checkpoint_flag_basic: {title: 'Flag'},
  checkpoint_fox_inu: {title: 'Inu'},
  checkpoint_gate_angel: {title: 'Angel Gate'},
  checkpoint_grave_halloween_2023: {title: 'Spooky Gravestone Checkpoint'},
  checkpoint_katana_basic: {title: 'Katana Checkpoint'},
  checkpoint_lantern_chinese: {title: 'Lantern Checkpoint'},
  checkpoint_lifebuoyflag_basic: {title: 'Lifesaver Checkpoint'},
  checkpoint_ninjabanner_basic: {title: 'Ninja Checkpoint'},
  checkpoint_northpole_2022: {title: 'North Pole Checkpoint'},
  checkpoint_orb_basic_pulsating: {title: 'Pulsating Orb'},
  checkpoint_pentagram_devil: {title: 'Devil Pentagram'},
  checkpoint_presents_2023: {title: 'Presents Checkpoint'},
  checkpoint_pumpkin_basic: {title: "Jack-o'-lantern Checkpoint"},
  checkpoint_scepter_royal: {title: 'Royal Scepter'},
  checkpoint_scubatanks: {title: 'Scuba Tank Checkpoint'},
  checkpoint_sir_duckton: {title: 'Sir Duckton'},
  checkpoint_snowman_2022: {title: 'Bob the Snowman Checkpoint'},
  checkpoint_steampunk_2024: {title: 'Mechanical Heart'},
  checkpoint_the_mountain: {title: 'The Mountain Checkpoint'},
  checkpoint_ufo_basic_beam: {title: 'UFO Checkpoint'},
  grapple_hook_arrow_heart: {title: "Cupid's Arrow"},
  grapple_hook_candycane: {title: 'Candy Cane Grapple'},
  grapple_hook_carott_basic: {title: 'Carrot'},
  grapple_hook_cheese_string: {title: 'String Cheese'},
  grapple_hook_easter_2023: {title: 'Bunny Pop Grapple'},
  grapple_hook_fish_rizzler: {title: 'Rizzler'},
  grapple_hook_foldingfan_basic: {title: 'Folding Fan Grapple'},
  grapple_hook_gingerbread_2023: {title: 'Gingerbread Grapple'},
  grapple_hook_hammer_steampunk: {title: 'Hammer Grapple'},
  grapple_hook_hotdog: {title: 'Hotdog Grapple'},
  grapple_hook_kite_basic: {title: 'Kite Grapple'},
  grapple_hook_kunai_basic: {title: 'Kunai Grapple'},
  grapple_hook_pen_marker: {title: 'Marker Grapple'},
  grapple_hook_rocket_basic: {title: 'Rocket Grapple'},
  grapple_hook_scythe_halloween_2023: {title: 'Scythe Grapple'},
  grapple_hook_shark_basic: {title: 'Sharky Grapple'},
  grapple_hook_shoge_basic: {title: 'Shoge Grapple'},
  grapple_hook_shovel_basic: {title: 'Shovel'},
  grapple_hook_spear_angel: {title: 'Angel Spear'},
  grapple_hook_spider_basic: {title: 'Frooble'},
  grapple_hook_stake_basic_wood: {title: 'Wooden Stake'},
  grapple_hook_sword_royal: {title: 'Royal Sword'},
  grapple_hook_trident_basic_gold: {title: 'Trident'},
  grapple_hook_trident_devil: {title: 'Devil Trident'},
  hand_sphere_basic: {title: 'Sphere Hands'},
  head_diver_oldschool: {title: 'Diving Helmet'},
  head_glasses_beard_christmas_2022: {title: 'Santa Beard'},
  head_glasses_cigar_noir_detective: {title: 'Cigar'},
  head_glasses_glasses_nerd: {title: 'Nerd Glasses'},
  head_glasses_hmd_meta_basic: {title: 'VR Headset'},
  head_glasses_horns_devil_basic: {title: 'Devil Horns'},
  head_glasses_mask_dragon_paper: {title: 'Paper Dragon Mask'},
  head_glasses_mask_oni_basic: {title: 'Oni Mask'},
  head_glasses_new_year_2024: {title: '2024 Glasses'},
  head_hat_antlers_2023: {title: 'Antlers'},
  head_hat_baseballcap_basic_darkgreen: {title: 'Green Baseball Cap'},
  head_hat_baseballcap_basic_darkred: {title: 'Red Baseball Cap'},
  head_hat_baseballcap_basic_pink: {title: 'Pink Baseball Cap'},
  head_hat_baseballcap_propeller_redblue: {title: 'Propeller Cap'},
  head_hat_bunny_ears_black: {title: 'Bunny Ears Black'},
  head_hat_bunny_ears_brown: {title: 'Bunny Ears Brown'},
  head_hat_bunny_ears_white: {title: 'Bunny Ears White'},
  head_hat_catears_piercing: {title: 'Cat Ears'},
  head_hat_cheese_basic: {title: 'Cheese Hat'},
  head_hat_christmas_2022: {title: 'Christmas Hat'},
  head_hat_contest_builder_tutorial: {title: 'Tutorial Builder Hat'},
  head_hat_cowboyhat_basic_dev: {title: 'Admin Hat'},
  head_hat_crown_royal: {title: 'Royal Crown'},
  head_hat_fedora_easter_2023: {title: 'Bunny Ear Fedora'},
  head_hat_fedora_noir_detective: {title: 'Fedora'},
  head_hat_halo_angel_basic: {title: 'Angel Halo'},
  head_hat_halo_angel_basic_detail: {title: 'Angel Halo With Detail Color'},
  head_hat_hatchet_halloween_2023: {title: 'Hatchet'},
  head_hat_headband_basic_black: {title: 'Black Headband'},
  head_hat_headband_basic_blue: {title: 'Blue Headband'},
  head_hat_headband_basic_red: {title: 'Red Headband'},
  head_hat_new_year_2024: {title: 'Party Hat 2024'},
  head_hat_ninja_basic: {title: 'Ninja Hat'},
  head_hat_steampunk_2024: {title: 'Gears of Love'},
  head_hat_sunhat_basic_moderator: {title: 'Moderator Hat'},
  head_hat_sunhat_basic_moderator_player_colors: {title: 'Moderator Hat Colors'},
  head_hat_tophat_basic_black: {title: 'Black Top Hat'},
  head_hat_tophat_basic_black_with_purple: {title: 'Black Top Hat With Purple'},
  head_hat_tophat_basic_black_with_red: {title: 'Black Top Hat With Red'},
  head_hat_tophat_basic_player_colors: {title: 'Top Hat With Character Colors'},
  head_hat_tophat_basic_white_with_cyan: {title: 'White Top Hat With Blue'},
  head_hat_tophat_heart: {title: 'Top Hat with a Heart'},
  head_hat_tree_christmas_2022: {title: 'Christmas Tree Hat'},
  head_hat_umbrella_basic: {title: 'Umbrella Hat'},
  head_hat_witch_basic: {title: 'Witch Hat'},
  head_space_basic: {title: 'Space Helmet'}
